# Generated by Django 2.2 on 2019-04-29 12:52

from django.db import migrations, models
import django.db.models.deletion
import marvel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=marvel.models.Group.get_upload_to)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('biography', models.TextField(blank=True)),
                ('eyes', models.CharField(blank=True, max_length=128)),
                ('hair', models.CharField(blank=True, max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=marvel.models.Character.get_upload_to)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marvel.Group')),
            ],
        ),
    ]
