# Generated by Django 2.2 on 2019-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='hero',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
